export const constants = {

    GET_STREAMS_REQUEST: 'STREAMS_REQUEST',
    GET_STREAMS_SUCCESS: 'STREAMS_SUCCESS',
    GET_STREAMS_FAILURE: 'STREAMS_FAILURE',

    GET_STREAM_REQUEST: 'GET_STREAM_REQUEST',
    GET_STREAM_SUCCESS: 'GET_STREAM_SUCCESS',
    GET_STREAM_FAILURE: 'GET_STREAM_FAILURE',

    GET_MYSTREAM_REQUEST: 'GET_MYSTREAM_REQUEST',
    GET_MYSTREAM_SUCCESS: 'GET_MYSTREAM_SUCCESS',
    GET_MYSTREAM_FAILURE: 'GET_MYSTREAM_FAILURE',
    
    UPDATE_MYSTREAM_REQUEST: 'UPDATE_MYSTREAM_REQUEST',
    UPDATE_MYSTREAM_SUCCESS: 'UPDATE_MYSTREAM_SUCCESS',
    UPDATE_MYSTREAM_FAILURE: 'UPDATE_MYSTREAM_FAILURE',

    FOLLOW_STREAM_REQUEST: 'FOLLOW_STREAM_REQUEST',
    FOLLOW_STREAM_SUCCESS: 'FOLLOW_STREAM_SUCCESS',
    FOLLOW_STREAM_FAILURE: 'FOLLOW_STREAM_FAILURE',

    RESET_STREAMS: 'RESET_STREAMS',
};

export default constants;
